# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

catalogdetail1:
  image:
    repository: public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail
    tag: "1.0"

catalogdetail2:
  image:
    repository: public.ecr.aws/u2g6w7p2/eks-workshop-demo/catalog_detail
    tag: "2.0"

productcatalog:
  image:
    repository: public.ecr.aws/u2g6w7p2/eks-workshop-demo/product_catalog
    tag: "1.0"

  env:
    - name: AGG_APP_URL
      value: "http://catalogdetail.workshop.svc.cluster.local:3000/catalogDetail"

frontend:
  image:
    repository: public.ecr.aws/u2g6w7p2/eks-workshop-demo/frontend_node
    tag: "2.0"

  env:
    - name: BASE_URL
      value: "http://productcatalog.workshop.svc.cluster.local:5000/products/"
